// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var add_task, add_task_now, assert, dump, throw_err, util;

  util = require('util');

  throw_err = function(msg) {
    throw new Error(msg || 'Unspecified Error');
  };

  assert = function(condition, msg) {
    if (!condition) {
      if ((msg != null) && typeof msg !== 'string') {
        dump(msg, 'Error Data Context');
      }
      return throw_err(msg || 'Assertion failed');
    }
  };

  dump = function(data, label, opts) {
    if (label == null) {
      label = 'unlabeled object';
    }
    if (opts == null) {
      opts = {};
    }
    if (opts.colors == null) {
      opts.colors = true;
    }
    if (opts.depth == null) {
      opts.depth = 4;
    }
    return util.debug(("" + label + "\n") + util.inspect(data, opts));
  };

  add_task = function(interval, cb) {
    return setInterval(cb, interval * 1000);
  };

  add_task_now = function(interval, cb) {
    cb();
    return add_task(interval, cb);
  };

  module.exports.throw_err = throw_err;

  module.exports.assert = assert;

  module.exports.dump = dump;

  module.exports.add_task = add_task;

  module.exports.add_task_now = add_task_now;

}).call(this);
