# See https://github.com/rogerwang/node-webkit/wiki/Manifest-format

name: planetscape
main: index.html
description: render of network-related data on a world map
version: 0.0.1

keywords:
  - planetscape
  - traceroute
  - network
  - hops
  - routing
  - maxmind
  - geoip
  - node-webkit

repositories:
  - type: git
    url: https://github.com/mk-fg/planetscape/
  - type: git
    url: http://fraggod.net/code/git/planetscape/

bugs: https://github.com/mk-fg/planetscape/issues

window:
  title: planetscape
  icon: planetscape-icon.png

  width: 800
  height: 500
  # min_width: 400
  # min_height: 200
  # max_width: 800
  # max_height: 600

  # resizable: false
  # show_in_taskbar: false
  # toolbar: false
  # frame: false
  # as_desktop: true
  # always-on-top: false
  # fullscreen: false
  # kiosk: false


maintainers:
  - &mk-fg
    name: Mike Kazantsev
    email: mk.fraggod@gmail.com
    web: http://fraggod.net

contributors:
  - *mk-fg

licenses:
  - type: WTFPL
    url: http://wtfpl.org/
