# See https://github.com/rogerwang/node-webkit/wiki/Manifest-format

name: planetscape
description: render of network-related data on a world map
version: 0.0.1

keywords:
  - planetscape
  - traceroute
  - network
  - hops
  - routing
  - maxmind
  - geoip
  - node-webkit

main: index.html

dependencies:
  geoip-lite: ~1.1.3
  mtr: ~0.2.1
  js-yaml: ~3.0.2

window:
  title: planetscape
  icon: images/icon.png

  width: 1280
  height: 900
  # min_width: 400
  # min_height: 200
  # max_width: 800
  # max_height: 600

  # resizable: false
  # show_in_taskbar: false
  # toolbar: false
  # frame: false
  # as_desktop: true
  # always-on-top: false
  # fullscreen: false
  # kiosk: false

## Fixes "InitializeSandbox() called with multiple threads in process gpu-process" with open ATI drivers
## Though WebGL in chromium is unusable anyway, so fuck it
# chromium-args: '--in-process-gpu'
# webkit:
#   # Defined in shell_switches.cc, but doesn't seem to be implemented (yet?)
#   webgl: true

# js-flags: '--help'
# js-flags: '--trace_exception'
# js-flags: '--log --logfile=-'

repositories:
  - type: git
    url: https://github.com/mk-fg/planetscape/
  - type: git
    url: http://fraggod.net/code/git/planetscape/

bugs: https://github.com/mk-fg/planetscape/issues

maintainers:
  - &mk-fg
    name: Mike Kazantsev
    email: mk.fraggod@gmail.com
    web: http://fraggod.net

contributors:
  - *mk-fg

licenses:
  - type: WTFPL
    url: http://wtfpl.org/
